### ISSUE TITLE
GYP Error-HELP Needed

### ISSUE THREAD

**Issue by Mexxy-lab** [insidesherpa/JPMC-tech-task-2#14]
Please see below screenshot for Task 3, tried installing the npm but keep getting these errors. nvm 11.0.0 is currently installed along with the right node version. Executing the npm install gives this error it doesn't complete the installation.

![image](https://user-images.githubusercontent.com/49109013/69515298-20157700-0f1c-11ea-9343-37402800d16a.png)

Any help would be greatly appreciated.

**Comment by jbf-insidesherpa** [comment]
@Mexxy-lab your issue should be addressed in the troubleshooting slides of the setup guide (slides 60-63/95): https://insidesherpa.s3.amazonaws.com/vinternships/companyassets/Sj7temL583QAYpHXD/setup_devenv_m2_v8.pdf

**Comment by Mexxy-lab** [comment]
Still having same issue even after including the path to python in the Environment variable and mapping npm to the only python version 3.8 i have installed. This was after changing to the latest python version 3.8. Below screenshot shows its mapped correctly after running pip --version command and latest python version. But am still getting same error.

Should i install the python in same repository as the JPMC-tech-task-3-PY3? I do not think this should be the problem here. Apparently python 8 isn't working also.

![image](https://user-images.githubusercontent.com/49109013/69663655-a92fc980-1054-11ea-8cbb-6bf86b19ddaf.png)

**Comment by jbf-insidesherpa** [comment]
@Mexxy-lab I don't think you did **npm config set python /path/to/executable/python** ( where /path/to/executable/python is the
directory where the python2.7.x binary is, for example in /usr/bin/python usually in linux/mac or
C:\\Python27 for Windows) This means you also need to have python2.7.x installed in your system.

**Comment by arinmsn** [comment]
@Mexxy-lab, I had the same issue and if none of the instructions work, download the node module as it contains all the dependencies you need. Before downloading the file, go through all steps again slowly. I hope you get it resolved!

**Comment by jbf-insidesherpa** [comment]
Thanks for the response @arinmsn . To be clear, you don't need to go through all steps again if you go for the copying of node_modules option (which is the last resort). All you need to have is your node and npm versions set properly. Then you should be able to do **npm start** w/o doing **npm install** anymore.

@Mexxy-lab I'm closing this issue now as it has been a while. Feel free to re-open  if you still have related issues
